### ISSUE TITLE
Can I run dispnet on non-GPU machine

### ISSUE THREAD

**Issue by Wanghaiyang0211** [lmb-freiburg/dispnet-flownet-docker#12]
I built dispnet-flownet-docker with CPU_ONLY = 1,it gives me the following error:
src/caffe/layers/data_augmentation_layer.cpp:179:30: error: ‘caffe_gpu_memcpy’ was not declared in this scope caffe_gpu_memcpy(this->blobs_[2]->count()*sizeof(float), tmp.mutable_gpu_data(), this->blobs_[2]->mutable_gpu_data());
src/caffe/layers/data_augmentation_layer.cpp: In instantiation of ‘void caffe::DataAugmentationLayer<Dtype>::adjust_blobs(std::vector<caffe::Blob<Dtype>*>) [with Dtype = double]’: src/caffe/layers/data_augmentation_layer.cpp:219:1:   required from here src/caffe/layers/data_augmentation_layer.cpp:179:30: error: ‘caffe_gpu_memcpy’ was not declared in this scope Makefile:580: recipe for target '.build_release/src/caffe/layers/data_augmentation_layer.o' failed 
make: *** [.build_release/src/caffe/layers/data_augmentation_layer.o] Error 1
Can I run dispnet using CPU-machine?
Thank you

**Comment by nikolausmayer** [comment]
No, our Caffe-based networks do not include CPU code.

You might be able to run the latest DispNet which is based on TensorFlow (see https://github.com/lmb-freiburg/netdef-docker or https://github.com/lmb-freiburg/netdef_models)

**Comment by Wanghaiyang0211** [comment]
> No, our Caffe-based networks do not include CPU code.
> 
> You might be able to run the latest DispNet which is based on TensorFlow (see https://github.com/lmb-freiburg/netdef-docker or https://github.com/lmb-freiburg/netdef_models)

**Comment by Wanghaiyang0211** [comment]
Thank you, I will try it later

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
