### ISSUE TITLE
Solver prototxt file to train from scratch

### ISSUE THREAD

**Issue by adhara123007** [lmb-freiburg/dispnet-flownet-docker#16]
Hi Niklolaus,

From the post (https://github.com/lmb-freiburg/dispnet-flownet-docker/issues/5) I gathered that your weight schedule is
loss6: [1.0, 0.5, 0, 0, 0, 0, 0]
loss5: [0.2, 1, 0.5, 0, 0, 0, 0]
loss4: [0, 0.2, 1, 0.5, 0, 0, 0]
loss3: [0, 0, 0.2, 1, 0.5, 0, 0]
loss2: [0, 0, 0, 0.2, 1, 0.5, 0]
loss1: [0, 0, 0, 0, 0.2, 1.0, 1.0] (highest trained resolution)

Did you use the same solver.prototxt file that is present in the folder for training with this weight schedule?
net: "../model/train.prototxt"
test_iter: 4370
test_interval: 10000
base_lr: 1e-4
lr_policy: "multistep"
gamma: 0.5
stepvalue: 200000
stepvalue: 350000
stepvalue: 500000
stepvalue: 650000
stepvalue: 800000
momentum: 0.9
weight_decay: 0.0004
display: 50

I tried training the netw

**Comment by nikolausmayer** [comment]
To the best of my knowledge, yes, but please keep in mind that that was quite a while ago..

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
