### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by yanzhou-li** [lmb-freiburg/dispnet-flownet-docker#17]
dear author:
your  synthetic dataset is cool! can you tell me how to use the `blender`  to create them?  how to set the `python API `such as the parameters of  `stereo`? and how to convert to `disparity` using the known configuration of the virtual stereo rig? can you give me a `script` or some advise ?
tks!

**Comment by nikolausmayer** [comment]
I cannot give you our code, but when I wrote it, I mostly used Blender to discover which operations I needed, and then looked up the API at https://docs.blender.org/api/2.75/contents.html. It was a lot of trial and error, and the documentation is not perfect, but Blender's Python console makes trying stuff out very fast.

For the depth→disparity conversion, you only need the standard formula (see https://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlowDatasets.en.html) and the parameters of your virtual camera (focal length and sensor size). Both are listed in Blender. If I remember correctly, the KITTI dataset also has some documentation on how to do this.

**Comment by yanzhou-li** [comment]
Thank you for your response! I‘ll try it.
