### ISSUE TITLE
Getting strange disparity map with DispNetCorr1D

### ISSUE THREAD

**Issue by lamerman** [lmb-freiburg/dispnet-flownet-docker#2]
I get strange output for the 0000000-imgL.png 0000000-imgR.png pair. I run the network like this:

`./run-network.sh -n DispNetCorr1D -v data/disparity-left-images.txt data/disparity-right-images.txt data/disparity-outputs.txt`

Then I convert the **pfm** to **pam** and then to **gif** with **netpbm** and get the following result:

![Image](https://image.ibb.co/hO9mBm/out.gif)

It does not seem to be correct. What can be wrong?

**Comment by nikolausmayer** [comment]
Hi,
as far as I can tell, PAM is an integer format, but PFM is intended for floating point values. How did you do the conversions?

**Comment by lamerman** [comment]
@nikolausmayer, I first used pfmtopam utility from the netpbm software package to convert pfm to pam. And then pamtogif to convert pam to gif.
Could you recommend some other conversion or viewing tools maybe?

**Comment by nikolausmayer** [comment]
I could not get the netpbm tools to work with PFM. I'm using CImg to read the PFM files (http://cimg.eu/reference/structcimg__library_1_1CImg.html#ad0dfcaee54123e2a7f2747ae212b7476), then I display them using CImg's CImgDisplay routines.
For Python, we actually have a code snippet for PFM I/O; see http://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlowDatasets.en.html

**Comment by lamerman** [comment]
@nikolausmayer thank you :) 

Using your code snippet I was able to visualize the data and it seemed to be correct.
