### ISSUE TITLE
Docker images help

### ISSUE THREAD

**Issue by OzzyW** [lmb-freiburg/dispnet-flownet-docker#3]
Hello,

Is it possible to access these docker images that were created or see the source code for the DispNet network?
I am not sure I understand where they were saved and if so how can I find them (I am new in using Docker containers)? 

Thanks for your great work!

**Comment by nikolausmayer** [comment]
Hi,

the docker images are stored on your local hard drive (but I don't remember exactly where). To "access" an image, the easiest option is to start an interactive shell in the container:
`docker run --rm -it dispflownet /bin/bash`
This is like SSH-ing into another computer, and gives you full access to the container's file system. If you want to import/export files to/from the container, use the "volume" option:
`docker run --rm --volume "${PWD}:/input-output:rw" -it dispflownet /bin/bash`
Your local working directory is then mounted as `/input-output` inside the container.

The Dockerfile just downloads our source code release from https://lmb.informatik.uni-freiburg.de/resources/software.php, so you could get it from there, too.

**Comment by OzzyW** [comment]
Thank you so much for the detailed answer. I tried through the link instead (it was not documented so I used flownet2 as reference which is not the best).  To get a disparity image I used Clmg like you said in one of the posts.  Is it possible to output in a different format then pfm and also how did you evaluate the D1 errors in KITTI (after using Cimg on the disparity image or is it possible straight from the pfm file)?

**Comment by nikolausmayer** [comment]
The PFM output is done by "PFMWriter" layers in the DispNet prototxt definitions. You could use any other output layer instead.

KITTI's D1 error can be evaluated on any format. The biggest challenge here is to convert either PFM into KITTI's PNG format, or vice versa, and that's not hard either (KITTI's SDK download provides example code to understand the format).

IIRC we did the evaluation in Python, using the PFM I/O code available on our [dataset download page](https://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlowDatasets.en.html) (CTRL+F "snippet").

**Comment by OzzyW** [comment]
Oh I see. I am actually new to Caffe too so one last question. If I update a layer do I need to run the whole makefile/caffe compilation process again or is there a shortcut for updating/compiling only for a layer/parts of a layer such as editing the pfmwriter.cpp for example?

Thank you so much for your help and have a nice weekend!

**Comment by nikolausmayer** [comment]
If you only change the "deploy" prototxt file, then you only change which layers will be instanced at runtime. In this case you can run the changed net directly without recompiling.

If you change the source code of the PFMWriter layer, then you have to recompile, but the build process will know that only this file has changed and compilation should be relatively fast.

If you add another layer, or you change the "caffe.proto" file (e.g. because you need new parameters for the PFMWriter), then the entire codebase needs to be rebuilt.

**Comment by OzzyW** [comment]
Thanks again for helping in my research! (I really hope your university pays you well to maintain this repo ;) )

**Comment by nikolausmayer** [comment]
I'm going to use this in my next salary negotiations :grin:
