### ISSUE TITLE
LMDB of KITTI2015 (how to deal with inf points?)

### ISSUE THREAD

**Issue by 77QIQI** [lmb-freiburg/dispnet-flownet-docker#6]
Hello,

In KITTI2015, the disp_gt is .png format. But in CVPR2018 Robust Challenge, it provides pfm format ground truth. However, the KITTI 2015 doesn't provide all pixels of the images (many inf-pfm / zero-png points). So how do you deal with these points?

I find that you change NAN to MAX(short) in convert_imageset_and_disparity.cpp. 
     `if(isnan(cv_disp.at<float>(y, x))){
                        value=std::numeric_limits<short>::max();}`

But for KITTI, should the inf points be ignored in the loss layer. Or do you ignore there inf points during flow augmentation layer?

What's more, the KITTI2015 images' size is not all same. For example, the weight ranges from 372 to 374.
So how to deal with it during making lmdb to adapt the concat and dummydata layer?

Thank you in advance.
Qiqi

**Comment by nikolausmayer** [comment]
> In KITTI2015, the disp_gt is .png format. But in CVPR2018 Robust Challenge, it provides pfm format ground truth. However, the KITTI 2015 doesn't provide all pixels of the images (many inf-pfm / zero-png points). So how do you deal with these points?

We treat the zero-png KITTI pixels as NaN and ignore them in the loss layer. The same can be done for inf-pfm.

> I find that you change NAN to MAX(short) in convert_imageset_and_disparity.cpp.
if(isnan(cv_disp.at<float>(y, x))){ value=std::numeric_limits<short>::max();}
But for KITTI, should the inf points be ignored in the loss layer. Or do you ignore there inf points during flow augmentation layer?

I don't remember what our flow augmentation does. Invalid pixels are probably just ignored.


> What's more, the KITTI2015 images' size is not all same. For example, the weight ranges from 372 to 374. So how to deal with it during making lmdb to adapt the concat and dummydata layer?

For training we crop all images to the size of the smallest one. For testing it does not matter as you can just reinitialize the network for each sample anyway.

**Comment by 77QIQI** [comment]
Thanks a lot!

**Comment by OzzyW** [comment]
Hey 77QIQI , did you mange to turn the KITTI images into LMBD and have some pointers?

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
